id: P005513
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19060
  title: དུས་རབས་ཀྱི་སྟེགས་བུ།
  author: ''
  volumes:
    ad9959efd23246b6ab6b0d1742876b74:
      image_group_id: I8LS19062
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
