id: P005513
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:46.411089
source_metadata:
  id: bdr:W8LS19060
  title: དུས་རབས་ཀྱི་སྟེགས་བུ།
  author: ''
  volumes:
    ad9959efd23246b6ab6b0d1742876b74:
      image_group_id: I8LS19062
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
